### ISSUE TITLE
Add TypeScript type declaration file

### ISSUE THREAD

**Issue by saschanaz** [w3c/webidl2.js#255]
Adding `index.d.ts` in the root directory will enable other packages to automatically read it to properly typecheck any use of webidl2.js.

Previously I had to contribute to DefinitelyTyped like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25092 but it's harder to maintain as it has a separate versioning system.

@marcoscaceres What do you think, as you previously stated a concern about adding TS support? https://github.com/w3c/webidl2.js/pull/55#issuecomment-277568070

**Comment by marcoscaceres** [comment]
I'm very comfortable about our TS support because we use the JSDoc style. What I'm uncomfortable with is writing pure TypeScript code and transpiling it. So, I'd be totally fine with as index.d.ts file so long as code in the project remains ES.

**Comment by ExE-Boss** [comment]
<https://github.com/microsoft/TypeScript/issues/7546> has been resolved [and is supported as of **TypeScript 3.7**](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#--declaration-and---allowjs).

**Comment by saschanaz** [comment]
Hey @ExE-Boss, you have been quite active for editing @types/webidl2. Are you interested in generating them right from the sources? I haven't been too active in this area so your help would be very precious.

**Comment by ExE-Boss** [comment]
Well, I tried it already, but I ran into <https://github.com/microsoft/TypeScript/issues/4433>.

**Comment by saschanaz** [comment]
Oh, TIL! Generating separate module definitions doesn't sound like a blocker for me though. My immediate blocker is that I have no way to generate .d.ts without also generating .js files.

**Comment by ExE-Boss** [comment]
[`emitDeclarationOnly`](https://www.typescriptlang.org/tsconfig#emitDeclarationOnly) does exactly that.

**Comment by saschanaz** [comment]
Thanks, and this is now interesting.

```
> npx tsc --declaration --allowJs --outDir types --emitDeclarationOnly                 
C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:82931
                throw e;
                ^

Error: Debug Failure. Unhandled class member kind! 33587200
    at serializePropertySymbol (C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33558:41)
    at serializePropertySymbolForInterface (C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33562:28)
    at C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33217:104
    at Object.flatMap (C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:388:25)
    at serializeInterface (C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33217:38)
    at serializeSymbolWorker (C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33146:25)
    at serializeSymbol (C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33096:38)
    at C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33077:25
    at Map.forEach (<anonymous>)
    at visitSymbolTable (C:\Users\Kagami\Documents\GitHub\webidl2.js\node_modules\typescript\lib\tsc.js:33076:33)
```

Maybe worth filing a bug...

**Comment by weswigham** [comment]
If you wanna workaround the issue for now (I have a PR out with a fix) - the interface merge(s) in `supplement.d.ts` are what's causing the declaration emitter to crash ❤️

**Comment by saschanaz** [comment]
Thanks @weswigham! Should I remove the supplement for now and instead define them in JSDoc? What would be the alternatives?

**Comment by weswigham** [comment]
Yeah, it'll work once the patch I have out is in.

**Comment by marcoscaceres** [comment]
[Earlier](https://github.com/w3c/webidl2.js/issues/255#issuecomment-451324426), I made a comment about our use of TS in this project. Over the last week, I've finally had a chance to really deep dive into TS. I now have a much better understanding of what it does and what it's actually for. Going forwards, I just wanted to go on the record that I'd feel quite comfortable with us adopting TS fully if we ever want to refactor this project (though I'd probably stay away from a few of the experimental things and just stick to the static analysis feature set of TS).

**Comment by saschanaz** [comment]
We still need more `@ts-check` on our codes so adding it for all files would be the first step for better TS use.

**Comment by saschanaz** [comment]
Somehow still doesn't work as expected, filed https://github.com/microsoft/TypeScript/issues/47358

**Comment by cyraid** [comment]
@saschanaz Did you get the reply on that bug report for the workaround? Is it possible to use here? `tsc --noEmit false --declaration [...]`

**Comment by saschanaz** [comment]
I think that works but the result should be refined to match the current DT types. Probably we can copypaste some of it.

**Comment by saschanaz** [comment]
Modern TypeScript is powerful and can import JSDoc from pure JS dependencies. I'm making the as a meta issue so that we put JSDoc everywhere needed.
