### ISSUE TITLE
Unable to parse CSSOM IDL (extended attribute on optional argument)

### ISSUE THREAD

**Issue by gsnedders** [w3c/webidl2.js#320]
```
interface CSSStyleDeclaration {
  void setProperty(CSSOMString property, [TreatNullAs=EmptyString] optional CSSOMString priority = "");
};
```

this gives:

```
(index):31 Uncaught ReferenceError: error is not defined
    at list (helpers.js:27)
    at argument_list (webidl2.js:239)
    at Function.parse (webidl2.js:470)
    at parse (webidl2.js:498)
    at Function.parse (webidl2.js:612)
    at Function.parse (webidl2.js:636)
    at interface_ (webidl2.js:685)
    at definition (webidl2.js:791)
    at definitions (webidl2.js:805)
    at parseByTokens (webidl2.js:816)
```

Probably because the appropriate module isn't imported.

Without the first argument there:

```
(index):31 Uncaught WebIDLParseError: Syntax error at line 2, since `interface CSSStyleDeclaration`:
  void setProperty([TreatNullAs=EmptyString]
                   ^ Unterminated operation
    at Tokeniser.error (https://w3c.github.io/webidl2.js/lib/tokeniser.js:195:11)
    at error (https://w3c.github.io/webidl2.js/lib/webidl2.js:23:15)
    at Function.parse (https://w3c.github.io/webidl2.js/lib/webidl2.js:471:38)
    at parse (https://w3c.github.io/webidl2.js/lib/webidl2.js:498:32)
    at Function.parse (https://w3c.github.io/webidl2.js/lib/webidl2.js:612:17)
    at Function.parse (https://w3c.github.io/webidl2.js/lib/webidl2.js:636:24)
    at interface_ (https://w3c.github.io/webidl2.js/lib/webidl2.js:685:17)
    at definition (https://w3c.github.io/webidl2.js/lib/webidl2.js:791:7)
    at definitions (https://w3c.github.io/webidl2.js/lib/webidl2.js:805:19)
    at parseByTokens (https://w3c.github.io/webidl2.js/lib/webidl2.js:816:15)
```

**Comment by saschanaz** [comment]
This is a parser bug, but anyway the IDL is wrong as far as I know, it should instead be:

```
interface CSSStyleDeclaration {
  void setProperty(CSSOMString property, optional [TreatNullAs=EmptyString] CSSOMString priority = "");
};
```
