### ISSUE TITLE
also mozilla  webidl: Attributes cannot accept sequence types

### ISSUE THREAD

**Issue by ihgazni2** [w3c/webidl2.js#392]
issue
------

    { WebIDLParseError: Syntax error at line 21, since `interface AccessibleNode`:
     attribute sequence<DOMString> states;
                                   ^ Attributes cannot accept sequence types
        at l.error (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:3920)
        at parse (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:13677)
        at Function.parse (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:19341)
        at Function.parse (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:21613)
        at o (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:25420)
        at i (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:25585)
        at /opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:25884
        at K (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:26014)
        at Module.Q (/opt/JS/WEBIDL2/webidl2.js/dist/webidl2.js:1:26168)
        at idl2s (repl:2:24)
      name: 'WebIDLParseError',
      bareMessage: 'Attributes cannot accept sequence types',
      context: 'Syntax error at line 21, since `interface AccessibleNode`:\n attribute sequence<DOMString> states;\n                               ^',
      line: 21,
      sourceName: undefined,
      input: 'states;\n\n  [Frozen,',
      tokens:
       [ { type: 'identifier',
           value: 'states',
           trivia: ' ',
           line: 21,
           index: 26 },
         { type: ';', value: ';', trivia: '', line: 21, index: 27 },
         { type: '[', value: '[', trivia: '\n\n  ', line: 23, index: 28 },
         { type: 'identifier',
           value: 'Frozen',
           trivia: '',
           line: 23,
           index: 29 },
         { type: ',', value: ',', trivia: '', line: 23, index: 30 } ] }

file
----

    https://dxr.mozilla.org/mozilla-central/source/dom/webidl/AccessibleNode.webidl

**Comment by saschanaz** [comment]
Because attributes must not have sequence type. See https://bugzilla.mozilla.org/show_bug.cgi?id=1236777 to fix this in their part.
