### ISSUE TITLE
Errors when parsing Chromium extensions API in IDL

### ISSUE THREAD

**Issue by sentialx** [w3c/webidl2.js#477]
Hello, I'm trying to parse Chromium extensions API in IDL with no luck.

Here's what I'm getting:
```
C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1
!function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.WebIDL2=t():e.WebIDL2=t()}(this,(function(){return function(e){var t={};function n(r){if(t[r])return t[r].exports;var s=t[r]={i:r,l:!1,exports:{}};return e[r].call(s.exports,s,s.exports,n),s.l=!0,s.exports}return n.m=e,n.c=t,n.d=function(e,t,r){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(n.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var s in e)n.d(r,s,function(t){return e[t]}.bind(null,s));return r},n.n=funct

WebIDLParseError: Syntax error at line 10, since `namespace autofillPrivate`:
  enum AddressField {
  ^ Missing return type
    at tokeniser_Tokeniser.error (C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:20350)
    at parse (C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:13168)
    at Function.parse (C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:24192)
    at Function.parse (C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:32300)
    at a (C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:34174)
    at C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:34301
    at L (C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:34433)
    at q (C:\Users\Senti\Desktop\idl-parser\node_modules\webidl2\dist\webidl2.js:1:34604)
    at Object.<anonymous> (C:\Users\Senti\Desktop\idl-parser\index.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1139:30) {
  name: 'WebIDLParseError',
  bareMessage: 'Missing return type',
  context: 'Syntax error at line 10, since `namespace autofillPrivate`:\n' +
    '  enum AddressField {\n' +
    '  ^',
  line: 10,
  sourceName: undefined,
  input: 'enum AddressField {\n    FULL_NAME,',
  tokens: [
    {
      type: 'enum',
      value: 'enum',
      trivia: '\n  // Fields used as part of an address.\n  ',
      line: 10,
      index: 3
    },
    {
      type: 'identifier',
      value: 'AddressField',
      trivia: ' ',
      line: 10,
      index: 4
    },
    { type: '{', value: '{', trivia: ' ', line: 10, index: 5 },
    {
      type: 'identifier',
      value: 'FULL_NAME',
      trivia: '\n    ',
      line: 11,
      index: 6
    },
    { type: ',', value: ',', trivia: '', line: 11, index: 7 }
  ]
}
```

The file:
https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/api/autofill_private.idl?originalUrl=https:%2F%2Fcs.chromium.org%2F

**Comment by saschanaz** [comment]
Unfortunately Chrome uses its own syntax for namespace nested items while a standard Web IDL namespace can only include operations and attributes.

It might be good to have some extensible API to support them, but so far webidl2.js only supports the standard syntax.

**Comment by saschanaz** [comment]
BTW, what's your use case to parse Chrome internal IDL?

**Comment by sentialx** [comment]
@saschanaz I would like to generate chrome.* API functions for my web browser made in Electron. What would you recommend for parsing those IDL files and output it to the [JSON scheme](https://source.chromium.org/chromium/chromium/src/+/master:chrome/common/extensions/api/tabs.json?originalUrl=https:%2F%2Fcs.chromium.org%2F)?

**Comment by saschanaz** [comment]
AFAIK there is no public library to parse browser-specific IDL. Each browser should have their own parser, so you might want to find and tweak it.

A potential second way is to fork this library and add support for Chrome specific syntax.

**Comment by sentialx** [comment]
@saschanaz Can I probably migrate this file to a valid WebIDL format? I removed the namespace and now it complains about this line:
```
DOMString[]? fullNames;
         ^ Dictionary member lacks a name
```

**Comment by saschanaz** [comment]
`sequency<DOMString>` is the standard syntax.

**Comment by sentialx** [comment]
@saschanaz Thanks, but now it throws:
```
sequency<DOMString> fullNames;
        ^ Unsupported generic type sequency
```
