### ISSUE TITLE
Unable to run tests locally

### ISSUE THREAD

**Issue by foolip** [w3c/webidl2.js#583]
I'm trying to do the same thing as the CI locally,
```
npm install
npm run build --if-present
npm test # or npx mocha
```

It fails like this:
```
(node:64743) ExperimentalWarning: The ESM module loader is experimental.

file:///Users/foolip/w3c/webidl2.js/test/util/collect.js:4
import { diff } from "jsondiffpatch";
         ^^^^
SyntaxError: The requested module 'jsondiffpatch' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'jsondiffpatch';
const { diff } = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:143:20)
    at async Loader.import (internal/modules/esm/loader.js:182:24)
    at async formattedImport (/Users/foolip/w3c/webidl2.js/node_modules/mocha/lib/esm-utils.js:7:14)
    at async Object.exports.loadFilesAsync (/Users/foolip/w3c/webidl2.js/node_modules/mocha/lib/esm-utils.js:55:20)
    at async singleRun (/Users/foolip/w3c/webidl2.js/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/foolip/w3c/webidl2.js/node_modules/mocha/lib/cli/run.js:362:5)
```

Versions:
- npm 6.14.8
- node 12.19.0
- macOS 11.2.3

Running `npm install` modifies `package-lock.json` and changes `lockfileVersion` from 2 to 1, so I suspect my `npm` might be old, but filing this issue before I try to upgrade it.

**Comment by foolip** [comment]
Hmm, the npm version in https://github.com/w3c/webidl2.js/runs/2440215759?check_suite_focus=true is

**Comment by foolip** [comment]
For unknown reasons upgrading to node 14.16.1 and npm 6.14.12 fixed the problem.

**Comment by saschanaz** [comment]
Hmm, I guess it's fixed somewhere between Node.j 12.19.0 and [12.21.0](https://github.com/w3c/webidl2.js/runs/2286961724?check_suite_focus=true)? 🤔

**Comment by saschanaz** [comment]
Per https://nodejs.org/en/blog/release/v12.20.0/, the CJS-to-ESM named exports support was backported to v12 by https://github.com/nodejs/node/commit/9eb1fa1924. Let's close this as fixed-by-upstream.
