### ISSUE TITLE
types of types

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webidl2.js#93]
For interfaces, const, attributes etc. that define a idlType, those types should themselves have a `type:` property saying what they are (e.g., "attribute-type", "constant-type").

**Comment by SaschaNaz** [comment]
I'm starting a bit confused about the hyphening, when we want to use space and when we want to use hyphen for the type name?

**Comment by SaschaNaz** [comment]
And what should the name be for returns types? Just `callback-type` or `callback-return-type`?

**Comment by SaschaNaz** [comment]
And BTW, `iterable()` has an idlType or an array of idlTypes. Do we want to make it a consistent array?

**Comment by marcoscaceres** [comment]
Ok, so the rule appears to be: if the type can match a name for display purpose (e.g., “callback interface”, “interface mixin”) we use space, otherwise use hyphen. 

And yeah about iterable, also setlike should be an array with a single item.

**Comment by saschanaz** [comment]
Sometimes an `idlType` has an `idlType` that includes an `idlType` with an `idlType`:

```json
"arguments": [
    {
        "optional": false,
        "variadic": false,
        "extAttrs": [],
        "idlType": {
            "sequence": true,
            "generic": "sequence",
            "nullable": false,
            "union": false,
            "idlType": {
                "sequence": false,
                "generic": "record",
                "nullable": false,
                "union": false,
                "idlType": [
                    {
                        "sequence": false,
                        "generic": null,
                        "nullable": false,
                        "union": false,
                        "idlType": "ByteString"
                    },
                    {
                        "sequence": false,
                        "generic": null,
                        "nullable": false,
                        "union": false,
                        "idlType": "any"
                    }
                ]
            }
        },
        "name": "param"
    }
]
```

Do we want to also add `sequence-type`, `record-type`, etc. for them? How about `union-type`?

**Comment by marcoscaceres** [comment]
that would be great, actually. That's part what I'm doing at the moment with my dynamically adding a parent (in ReSpec) to work out the type's type.

**Comment by saschanaz** [comment]
That sounds essentially #85 😄. Can you point your related ReSpec commits if you pushed so that I can understand your use case better?

**Comment by marcoscaceres** [comment]
I've not pushed my local the code up yet, but essentially I am deriving the "type" for a data-attribute. For example:

```HTML
<a dataset-idl-type="attribute-type">DOMString</a>
```

So, to do that, I call `getTypeFromParent()`, which just combines into, for example, "attribute-type": 

```JS
function getTypeFromParent({ parent }) {
  if (!parent) {
    return "";
  }
  if (parent.hasOwnProperty("type")) {
    return parent.type + "-type";
  }
  return getTypeFromParent(parent);
}
```

**Comment by saschanaz** [comment]
That is helpful, thanks!

**Comment by saschanaz** [comment]
Oops, not completely fixed yet.

**Comment by saschanaz** [comment]
We covered attribute-type, const-type, dictionary-type, typedef-type, and return-type. Is there anything still needed before a potential release?

**Comment by marcoscaceres** [comment]
I think we should be good to go. I'll publish soon.

**Comment by marcoscaceres** [comment]
@saschanaz, sorry, can you seem to be getting errors locally with `npm test`:

```
  1) Parses all of the IDLs to produce the correct ASTs
       should produce the same AST for /Users/marcos/Dropbox/repos/w3c/webidl2.js/test/syntax/idl/record.widl:
     Error: expect(received).toBeFalsy()

Expected value to be falsy, instead received
  {"0": {"members": {"1": {"idlType": {"idlType": {"1": {"idlType": {"0": {"type": ["return-type", null]}, "1": {"type": ["return-type", null]}, "_t": "a"}, "type": [null, "return-type"]}, "_t": "a"}}}, "_t": "a"}}, "_t": "a"}
      at Context.it (test/syntax.js:11:29)

  2) Parses all of the IDLs to produce the correct ASTs
       should produce the same AST for /Users/marcos/Dropbox/repos/w3c/webidl2.js/test/syntax/idl/typedef-union.widl:
     Error: expect(received).toBeFalsy()

Expected value to be falsy, instead received
  {"0": {"idlType": {"idlType": {"0": {"type": ["typedef-type", null]}, "1": {"type": ["typedef-type", null]}, "2": {"type": ["typedef-type", null]}, "3": {"type": ["typedef-type", null]}, "_t": "a"}, "type": [null, "typedef-type"]}}, "_t": "a"}
      at Context.it (test/syntax.js:11:29)
```

I haven't had a chance to poke around at those. Could you take a look?

**Comment by saschanaz** [comment]
Oops, quickly pushed ac7ef08. Sorry!

**Comment by marcoscaceres** [comment]
No problem :) Thanks for fixing!

**Comment by cyraid** [comment]
Is there anyone that updates the typescript `@types/webidl2` ? It seems the typescript side hasn't been updated to include argument-type, const-type etc.

**Comment by saschanaz** [comment]
That one is indeed undermaintained and it should ideally be autogenerated: #255
